version: "3.8"

services:
  accounts-storage-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=account_storage
      - DB_PORT=5433
    depends_on:
      - accounts-storage-db
    networks:
      - accounts-storage-network

  accounts-storage-db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=accounts_storage
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - accounts-storage-network

  accounts-storage-nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - accounts-storage-network

networks:
  accounts-storage-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
