shutdown_timeout = 5
bind_addres = ":8080"
log_level = "debug"
# database_type = "sql"
database_type = "local"
database_url = "host=localhost user=postgres password=password dbname=account_storage port=5433 sslmode=disable"
